[package]
name = "chearmyp_abstract_token"
version = "0.1.0-dev"
authors = ["Kenneth Trecy Tobias <33564322+KennethTrecy@users.noreply.github.com>"]
edition = "2018"

[dependencies.chearmyp_abstract_source]
git = "http://chearmyp.local/chearmyp_abstract_source"
tag = "v0.1.1"

[features]
default = []
no_std = ["chearmyp_abstract_source/no_std"]
